{% set name = "neuralcoref" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23aee7418edf5c2e90b3f9f15931563b07ded8c59de386ae654b403322430ad9

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [(py27) or (win and vc<14)]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - wheel
    - jsonschema >=2.6.0
    - spacy >=2.1.0
  run:
    - python
    - numpy >=1.15.0
    - boto3
    - requests
    - jsonschema >=2.6.0
    - spacy >=2.1.0

test:
  requires:
    - pip
    - pytest
    - spacy-model-en_core_web_sm >=2.1
  imports:
    - neuralcoref
    - neuralcoref.tests
    - neuralcoref.train
  commands:
    - pytest --pyargs neuralcoref
    - pip check

about:
  home: https://github.com/huggingface/neuralcoref
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Coreference Resolution in spaCy with Neural Networks"
  doc_url: https://huggingface.co/coref/
  dev_url: https://github.com/huggingface/neuralcoref

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
